# RootNet — R8/ProGuard rules
# (v2.2: no Xray engine, no AdMob/Unity. Adivery is the ONLY ad network — its AAR
# ships its own consumer rules; the explicit keeps below are belt-and-braces for
# release builds.)

# ── WorkManager / Room (AGP 9 R8 full-mode fix) ──────────────────────────────
# WorkManager is auto-initialized by androidx.startup BEFORE Application.onCreate.
# Its Room database implementation (androidx.work.impl.WorkDatabase_Impl) is
# created via reflection (Room.databaseBuilder), so R8's full mode sees it as
# unused and strips it from RELEASE builds → instant startup crash:
#   "Unable to get provider androidx.startup.InitializationProvider"
#   "Failed to create an instance of androidx.work.impl.WorkDatabase"
# Debug builds are unaffected (no minification). Rules from AGP9-era fix.
-keep class androidx.work.impl.** { *; }
-keep class * extends androidx.work.ListenableWorker {
    <init>(android.content.Context, androidx.work.WorkerParameters);
}

# ── Adivery Ads (v2.2 — the only ad network) ─────────────────────────────────
# The AAR ships its own consumer rules (auto-merged), but keep them explicitly
# for release builds: the SDK uses reflection + a JS bridge (WebView mediation)
# and the reward callback must survive R8.
-keep class com.adivery.sdk.** { *; }
-keepattributes JavascriptInterface
-keep class android.webkit.JavascriptInterface { *; }
# Adivery's AAR statically references optional mediation networks (MBridge /
# Mintegral, AdMob, Unity, ...) that this app does not ship. Generated by AGP
# R8 — suppress.
-dontwarn com.mbridge.msdk.**
-dontwarn com.google.android.gms.ads.**
-dontwarn com.unity3d.ads.**
-dontwarn com.unity3d.services.**
